_target_: otg.generate_included_gwas_catalog_studies.GWASCatalogInclusionGenerator
catalog_study_files: ${datasets.catalog_studies}
catalog_ancestry_files: ${datasets.catalog_ancestries}
catalog_associations_file: ${datasets.catalog_associations}
variant_annotation_path: ${datasets.variant_annotation}
gwas_catalog_study_curation_file: ${datasets.gwas_catalog_study_curation}
harmonised_studies: ???
criteria: ???
inclusion_list_path: ???
exclusion_list_path: ???
