# Default config
defaults:
  - finngen
# Additional config
finngen_phenotype_table_url: ${datasets.finngen_phenotype_table_url}
finngen_release_prefix: ${datasets.finngen_release_prefix}
finngen_sumstat_url_prefix: ${datasets.finngen_sumstat_url_prefix}
finngen_sumstat_url_suffix: ${datasets.finngen_sumstat_url_suffix}
finngen_study_index_out: ${datasets.finngen_study_index}
