# Default config
defaults:
  - study_locus_overlap
# Additional config
study_locus_path: ${datasets.outputs}/study_locus
study_index_path: ${datasets.outputs}/catalog_study_index
study_locus_overlap_path: ${datasets.outputs}/study_locus_overlap
