# Default config
defaults:
  - variant_annotation
# Additional config
gnomad_genomes: ${datasets.gnomad_gnomes}
chain_38_to_37: ${datasets.chain_hail_38_37}
variant_annotation_path: ${datasets.variant_annotation}
