_target_: otg.variant_annotation.VariantAnnotationStep

defaults:
    - session: dataproc
    - start_hail: true

gnomad_genomes: ${datasets.gnomad_genomes}
chain_38_to_37: ${datasets.chain_hail_38_37}
variant_annotation_path: ${datasets.variant_annotation}
