defaults:
  - locus_to_gene

run_mode: train
wandb_run_name: null
hf_hub_repo_id: opentargets/locus_to_gene
model_path: ${datasets.l2g_model}
predictions_path: ${datasets.l2g_predictions}
credible_set_path: ${datasets.credible_set}
variant_gene_path: ${datasets.variant_to_gene}
colocalisation_path: ${datasets.colocalisation}
study_index_path: ${datasets.study_index}
gold_standard_curation_path: ${datasets.l2g_gold_standard_curation}
gene_interactions_path: ${datasets.gene_interactions}
feature_matrix_path: ${datasets.l2g_feature_matrix}
write_feature_matrix: true
hyperparameters:
  n_estimators: 100
  max_depth: 5
  loss: log_loss
download_from_hub: true
features_list:
  # average distance of all tagging variants to gene TSS
  # - distanceTssMean
  # minimum distance of all tagging variants to gene TSS
  # - distanceTssMinimum
  # max CLPP for each (study, locus, gene) aggregating over a specific qtl type
  - eQtlColocClppMaximum
  - pQtlColocClppMaximum
  - sQtlColocClppMaximum
  - tuQtlColocClppMaximum
  # max H4 for each (study, locus, gene) aggregating over a specific qtl type
  - eQtlColocH4Maximum
  - pQtlColocH4Maximum
  - sQtlColocH4Maximum
  - tuQtlColocH4Maximum
