defaults:
  - locus_to_gene

run_mode: predict
model_path: null
predictions_path: ${datasets.l2g_predictions}
credible_set_path: ${datasets.credible_set}
variant_index_path: ${datasets.variant_index}
colocalisation_path: ${datasets.colocalisation}
study_index_path: ${datasets.study_index}
