name: genetics_etl_python
inputs: ${environment.storage}/input
outputs: ${environment.storage}/${datarelease.version}/output/python_etl/${datarelease.outputFormat}

coloc:
  inputs:
    study_locus_idx: gs://ot-team/irene/study_locus_v3 # where credsets are stored
    study_idx: gs://genetics_etl_python_playground/input/study_index
    #TOOD: to update
    sumstats_filtered: gs://genetics-portal-dev-sumstats/filtered/significant_window_2mb_union
  outputs:
    coloc: ${etl.outputs}/coloc
  parameters:
    # priorc1 Prior on variant being causal for trait 1
    priorc1: 1e-4
    # priorc2 Prior on variant being causal for trait 2
    priorc2: 1e-4
    # priorc12 Prior on variant being causal for traits 1 and 2
    priorc12: 1e-5
  machine: ${machine.coloc}

v2g:
  inputs:
    variant_annotation: ${etl.outputs}/variant_annotation
    variant_index: ${etl.outputs}/variant_index
    vep_consequences: gs://genetics-portal-data/lut/vep_consequences.tsv
    # Originally gs://genetics-portal-input/v2g_input/grch37_to_grch38.over.chain
    liftover_chain_file: ${etl.inputs}/v2g_input/grch37_to_grch38.over.chain
    # Originally gs://genetics-portal-input/v2g_input/geneset.protein_coding.parquet
    gene_index: ${etl.inputs}/v2g_input/targets
    # An atlas of active enhancers across human cell types and tissues
    # Originally: gs://genetics-portal-input/v2g_input/andersson2014/enhancer_tss_associations.bed
    anderson_file: ${etl.inputs}/v2g_input/andersson2014/enhancer_tss_associations.bed
    # Lineage-Specific Genome Architecture Links Enhancers and Non-coding Disease Variants to Target Gene Promoters
    # Originally gs://genetics-portal-input/v2g_input/javierre_2016_preprocessed.parquet
    javierre_dataset: ${etl.inputs}/v2g_input/javierre_2016_preprocessed.parquet
    # A compendium of promoter-centered long-range chromatin interactions in the human genome
    # Originally gs://genetics-portal-raw/pchic_jung2019/jung2019_pchic_tableS3.csv
    jung_file: ${etl.inputs}/v2g_input/pchic_jung2019/jung2019_pchic_tableS3.csv
    # The accessible chromatin landscape of the human genome
    # Originally: gs://genetics-portal-input/v2g_input/thurman2012/genomewideCorrs_above0.7_promoterPlusMinus500kb_withGeneNames_32celltypeCategories.bed8.gz
    thurman_file: ${etl.inputs}/v2g_input/thurman2012/genomewideCorrs_above0.7_promoterPlusMinus500kb_withGeneNames_32celltypeCategories.bed8.gz
  outputs:
    v2g: ${etl.outputs}/v2g
  parameters:
    partition_count: 400
    liftover_max_length_difference: 100
    tss_distance_threshold: 500000
    approved_biotypes:
      - protein_coding
      - 3prime_overlapping_ncRNA
      - antisense
      - bidirectional_promoter_lncRNA
      - IG_C_gene
      - IG_D_gene
      - IG_J_gene
      - IG_V_gene
      - lincRNA
      - macro_lncRNA
      - non_coding
      - sense_intronic
      - sense_overlapping
  machine: ${machine.v2g}

variant_annotation:
  inputs:
    gnomad_file: gs://gcp-public-data--gnomad/release/3.1.2/ht/genomes/gnomad.genomes.v3.1.2.sites.ht
    chain_file: gs://hail-common/references/grch38_to_grch37.over.chain.gz
  outputs:
    variant_annotation: ${etl.outputs}/variant_annotation
  machine: ${machine.variant_annotation}

variant_index:
  inputs:
    variant_annotation: ${etl.outputs}/variant_annotation
    credible_sets: ${etl.outputs}/credible_sets
  outputs:
    variant_index: ${etl.outputs}/variant_index
    variant_invalid: ${etl.outputs}/invalid/credible_sets
  machine: ${machine.default}

gwas_ingest:
  inputs:
    variant_annotation: gs://ot-team/dsuveges/variant_annotation/2022-08-11
    gwas_catalog_associations: ${etl.inputs}/v2d/gwas_catalog_v1.0.2-associations_e107_r2022-09-14.tsv
    gwas_catalog_studies: ${etl.inputs}/v2d/gwas-catalog-v1.0.3-studies-r2022-09-14.tsv
    gwas_catalog_ancestries: ${etl.inputs}/v2d/gwas-catalog-v1.0.3-ancestries-r2022-09-14.tsv
    summary_stats_list: ${etl.inputs}/v2d/harmonised_list.txt
  outputs:
    gwas_catalog_associations: ${etl.outputs}/gwas_catalog_associations
    gwas_catalog_studies: ${etl.outputs}/gwas_catalog_studies
  parameters:
    ingest_unpublished_studies: False
    p_value_cutoff: 5e-8
  machine: ${machine.default}

tissue_enrichment:
  inputs:
    tissue_annotations: gs://genetics-portal-dev-analysis/xg1/EPIMAP/CHEERS_annotations/Full_epimap.parquet
    summary_stats_credible_set: gs://genetics-portal-dev-analysis/xg1/CHEERS_credible_set/FM_220401_hg19.parquet
    pics_credible_set: gs://genetics-portal-dev-analysis/xg1/CHEERS_credible_set/Non_sumstat_hg19.parquet
  outputs:
    summary_stats_enrichment: gs://genetics-portal-dev-analysis/xg1/CHEERS_enrichments/sumstats_enrichments/results.parquet
    pics_enrichment: gs://genetics-portal-dev-analysis/xg1/pics_enrichments/results.parquet
    annotations_hg38: gs://genetics-portal-dev-analysis/xg1/EPIMAP/CHEERS_annotations/Full_epimap_hg38.parquet
  parameters:
    min_assoc_loci: 5
  machine: ${machine.default}
