name: genetics_etl_python
inputs: ${environment.storage}/input
outputs: ${environment.storage}/${datarelease.version}/output/python_etl/${datarelease.outputFormat}/

coloc:
  inputs:
    credible_set: ${etl.inputs}/220224_merged_credset/
    phenotype_id_gene: ${etl.inputs}/phenotype_id_gene_luts/
    #TOOD: to update
    sumstats_filtered: gs://genetics-portal-dev-sumstats/filtered/significant_window_2mb_union
  outputs:
    coloc: ${etl.outputs}/coloc
  parameters:
    # priorc1 Prior on variant being causal for trait 1
    priorc1: 1e-4
    # priorc2 Prior on variant being causal for trait 2
    priorc2: 1e-4
    # priorc12 Prior on variant being causal for traits 1 and 2
    priorc12: 1e-5
  machine: ${machine.coloc}

v2g:
  inputs:
    gene_index: ${etl.inputs}/v2g_input/targets_correct_tss
    variant_index: ${etl.outputs}/variant_index
  parameters:
    partition_count: 400
    tss_distance_threshold: 500000
  outputs:
    v2g_distance: ${etl.outputs}/v2g_distance

variant_annotation:
  inputs:
    gnomad_file: gs://gcp-public-data--gnomad/release/3.1.2/ht/genomes/gnomad.genomes.v3.1.2.sites.ht
    chain_file: gs://hail-common/references/grch38_to_grch37.over.chain.gz
  outputs:
    variant_annotation: ${etl.outputs}/variant_annotation_broadcast_part
  parameters:
    partition_count: 400
  machine: ${machine.variant_annotation}

variant_index:
  inputs:
    variant_annotation: ${etl.outputs}/variant_annotation
    credible_sets: ${etl.outputs}/credible_sets
  outputs:
    variant_index: ${etl.outputs}/variant_index
    variant_invalid: ${etl.outputs}/invalid/credible_sets
  machine: ${machine.default}

gwas_ingest:
  inputs:
    variant_annotation: gs://ot-team/dsuveges/variant_annotation/2022-08-11
    gwas_catalog_associations: ${etl.inputs}/v2d/gwas_catalog_v1.0.2-associations_e107_r2022-09-14.tsv
    gwas_catalog_studies: ${etl.inputs}/v2d/gwas-catalog-v1.0.3-studies-r2022-09-14.tsv
    gwas_catalog_ancestries: ${etl.inputs}/v2d/gwas-catalog-v1.0.3-ancestries-r2022-09-14.tsv
    summary_stats_list: ${etl.inputs}/v2d/harmonised_list.txt
  outputs:
    gwas_catalog_associations: ${etl.outputs}/gwas_catalog_associations
    gwas_catalog_studies: ${etl.outputs}/gwas_catalog_studies
  parameters:
    ingest_unpublished_studies: False
    p_value_cutoff: 5e-8
  machine: ${machine.default}
