version: 1
labels:
  - label: "XS"
    size:
      exclude-files: ["poetry.lock"]
      below: 10
  - label: "S"
    size:
      exclude-files: ["poetry.lock"]
      above: 9
      below: 100
  - label: "M"
    size:
      exclude-files: ["poetry.lock"]
      above: 100
      below: 500
  - label: "L"
    size:
      exclude-files: ["poetry.lock"]
      above: 499
      below: 1000
  - label: "XL"
    size:
      exclude-files: ["poetry.lock"]
      above: 999
  - label: "airflow"
    files:
      - "src/airflow/.*"
  - label: "Documentation"
    files:
      - "docs/.*"
  - label: "Dataset"
    files:
      - "src/dataset/.*"
  - label: "Method"
    files:
      - "src/method/.*"
  - label: "Datasource"
    files:
      - "src/datasource/.*"
  - label: "Feature"
    title: "feat:.*"
  - label: "Bug"
    title: "fix:.*"
  - label: "Refactor"
    title: "refactor:.*"
  - label: "Chore"
    title: "chore:.*"
  - label: "CI"
    title: "ci:.*"
  - label: "Test"
    title: "test:.*"
  - label: "Documentation"
    title: "docs:.*"
  - label: "Performance"
    title: "perf:.*"
  - label: "Build"
    title: "build:.*"
  - label: "Revert"
    title: "revert:.*"
  - label: "Mergeable"
    mergeable: true
