site_name: Genetics Portal Pipeline

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        crystal:
          selection:
            filters:
              - "!^_[^_]"
  - section-index
  - git-revision-date-localized
  - autolinks
  - minify:
      minify_html: true

repo_name: opentargets/genetics_etl_python
repo_url: https://github.com/opentargets/genetics_etl_python

theme:
  name: "material"
  favicon: assets/favicon.png
  logo: assets/otlogo.png

  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/genetics_etl_python
