site_name: Genetics Portal Pipeline

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        crystal:
          selection:
            filters:
              - "!^_[^_]"
  - section-index
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      exclude:
        - index.md
  - autolinks
  - minify:
      minify_html: true
  - exclude:
      glob:
        - assets/schemas/*
  # trigger scripts (e.g. schema generator)
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "scripts.schemadocs:main"
  # Show git commiters in the footer
  - git-committers:
      repository: opentargets/genetics_etl_python
      branch: main

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: "docs"

repo_name: opentargets/genetics_etl_python
repo_url: https://github.com/opentargets/genetics_etl_python

theme:
  name: "material"
  favicon: assets/favicon.png
  logo: assets/otlogo.png
  custom_dir: docs/assets/overrides

  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/genetics_etl_python

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js
