[tool.poetry]
name = "otgenetics"
version = "0.1.4"
description = "Open targets Genetics Portal Python ETL"
authors = ["Open Targets core team"]
license = "Apache License v2"
packages = [
    { include = "otg", from = "src"},
]

[tool.poetry.scripts]
otg = "otg.cli:main"

[tool.poetry.dependencies]
python = "3.8.15"
pyspark = "3.1.3"
scipy = "^1.6.1"
hydra-core = "^1.2.0"
pyliftover = "^0.4"
numpy = "^1.23.2"
hail = "^0.2.98"

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"
black = {version = "^22.6.0", allow-prereleases = true}
flake8 = "^5.0.4"
mypy = "^0.971"
flake8-annotations = "^2.9.1"
flake8-broken-line = "0.5.0"
flake8-bugbear = "22.7.1"
flake8-comprehensions = "3.10.0"
flake8-eradicate = "1.3.0"
flake8-quotes = "3.3.1"
flake8-simplify = "0.19.3"
flake8-tidy-imports = "4.8.0"
flake8-type-checking = "2.1.2"
flake8-typing-imports = "1.12.0"
flake8-use-fstring = "1.4"
pep8-naming = "^0.13.2"
interrogate = "^1.5.0"
isort = "^5.10.1"
darglint = "^1.8.1"
flake8-docstrings = "^1.6.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.0"
mkdocstrings-python = "^0.7.1"
mkdocs-material = "*"
mkdocs-section-index = "^0.3.4"
mkdocs-git-revision-date-localized-plugin = "^1.1.0"
mkdocs-autolinks-plugin = "^0.6.0"
mkdocs-minify-plugin = "^0.5.0"
mkdocs-awesome-pages-plugin = "^2.8.0"
mkdocs-simple-hooks = "^0.1.5"
mkdocs-exclude = "^1.0.2"
mkdocs-git-committers-plugin-2 = "^1.1.1"
lxml = "^4.9.2"


[tool.poetry.group.tests.dependencies]
pytest-cov = "^4.0.0"
pytest-sugar = "^0.9.5"
pandas = "<1.5.0"
dbldatagen = "^0.3.1"
pyparsing = "^3.0.9"
pytest = "^7.2.2"


[tool.poetry.group.dev.dependencies]
ipython = "^8.5.0"
flake8-class-attributes-order = "^0.1.3"
ipykernel = "^6.19.0"
flake8-pytest-style = "^1.7.2"
google-cloud-dataproc = "^5.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.interrogate]
fail-under = 95
color = true
exclude = ["dist"]

[tool.pytest.ini_options]
addopts = "--ignore=deprecated_tests"

[[tool.mypy.overrides]]
module = "google.protobuf.duration_pb2"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "yaml"
ignore_missing_imports = true
