[tool.poetry]
name = "genetics_etl_python"
version = "0.1.0"
description = "Open targets Genetics Portal Python ETL"
authors = ["Open Targets core team"]
license = "Apache License v2"
exclude = ["src/*.py"]
packages = [
    { include = "**/*.py", from = "src"},
]
[tool.poetry.dependencies]
python = "^3.8"
hydra-core = "^1.2.0"

[tool.poetry.dev-dependencies]
pyspark = "^3.3.0"
numpy = "^1.23.2"
pre-commit = "^2.15.0"
black = {version = "^22.6.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
