[tool.poetry]
name = "otgenetics"
version = "0.1.3"
description = "Open targets Genetics Portal Python ETL"
authors = ["Open Targets core team"]
license = "Apache License v2"
packages = [
    { include = "etl", from = "src"},
]
[tool.poetry.dependencies]
python = "3.8.13"
pyspark = "3.1.3"
scipy = "^1.6.1"
hydra-core = "^1.2.0"
pyliftover = "^0.4"
numpy = "^1.23.2"
gcsfs = "^2022.8.2"
pytest = "^7.1.3"
hail = "^0.2.98"

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"
black = {version = "^22.6.0", allow-prereleases = true}
flake8 = "^5.0.4"
mypy = "^0.971"
flake8-annotations = "^2.9.1"
flake8-broken-line = "0.5.0"
flake8-bugbear = "22.7.1"
flake8-comprehensions = "3.10.0"
flake8-eradicate = "1.3.0"
flake8-quotes = "3.3.1"
flake8-simplify = "0.19.3"
flake8-tidy-imports = "4.8.0"
flake8-type-checking = "2.1.2"
flake8-typing-imports = "1.12.0"
flake8-use-fstring = "1.4"
pep8-naming = "^0.13.2"
interrogate = "^1.5.0"
isort = "^5.10.1"
darglint = "^1.8.1"
flake8-docstrings = "^1.6.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.0"
mkdocstrings-python = "^0.7.1"
mkdocs-material = "*"
mkdocs-section-index = "^0.3.4"
mkdocs-git-revision-date-localized-plugin = "^1.1.0"
mkdocs-autolinks-plugin = "^0.6.0"
mkdocs-minify-plugin = "^0.5.0"


[tool.poetry.group.tests.dependencies]
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
pytest-sugar = "^0.9.5"


[tool.poetry.group.dev.dependencies]
ipython = "^8.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.interrogate]
fail-under = 95
color = true
exclude = ["dist"]
