_target_: otg.l2g.LocusToGeneStep
etl:
  _target_: otg.common.session.ETLSession
  spark_uri: "local[*]"
  app_name: "ot_genetics_local"
  write_mode: "overwrite"
run_mode: train
study_locus_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_study_locus
study_locus_overlap_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_study_locus_overlap
variant_gene_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_v2g
study_index_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_study_index
colocalisation_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_colocalisation
gold_standard_curation_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/curation.json
gene_interactions_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/interaction
hyperparameters:
  max_depth: 5
