_target_: otg.l2g.LocusToGeneStep
run_mode: train
defaults:
  - _self_
  - /etl: local
  - /dataset@variant_annotation: variant_annotation_from_file
  - /dataset@study_locus: study_locus_from_file
  - /dataset@l2g_model: locus_to_gene_model_from_file
  - /dataset@v2g: variant_to_gene_from_file
  - /dataset@colocalisation: colocalisation
  - /dataset@study_index: study_index_from_file
  - /dataset@study_locus_overlap: study_locus_overlap_from_file
  - /dataset@l2g_curation: locus_to_gene_curation
  - /dataset@gene_interactions: gene_interactions_from_file

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

hyperparameters:
  max_depth: 5
  loss_function: logloss

inputs:
  _target_: otg.gold_standard.GoldStandard
  _partial_: true
  gold_standard_curation: gs://genetics_etl_python_playground/input/l2g/gold_standard/curation.json
  gene_interactions: gs://open-targets-pre-data-releases/23.02/output/etl/parquet/interactions
  study_locus: gs://genetics_etl_python_playground/input/l2g_input/mock_study_locus
feature_inputs:
  v2g: gs://genetics_etl_python_playground/input/l2g_input/mock_v2g
  colocalisation: gs://genetics_etl_python_playground/input/l2g_input/mock_colocalisation
  study_index: gs://genetics_etl_python_playground/input/l2g_input/mock_study_index
outputs:
  model: gs://genetics_etl_python_playground/output/XX.XX/l2g/model
  predictions: gs://genetics_etl_python_playground/output/l2g/predictions
