_target_: otg.l2g.LocusToGeneStep
run_mode: train
study_locus_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_study_locus
study_locus_overlap_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_study_locus_overlap
variant_gene_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_v2g
study_index_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_study_index
colocalisation_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/mock_colocalisation
gold_standard_curation_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/curation.json
feature_matrix_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/feature_matrix_221107_transformed
features_list:
  - dist_tss_ave # average distance of all tagging variants to gene TSS
  - dist_tss_min # minimum distance of all tagging variants to gene TSS
  - eqtl_max_coloc_clpp_local # max clpp for each (study, locus, gene) aggregating over all eQTLs
  - eqtl_max_coloc_clpp_nbh # max clpp for each (study, locus) aggregating over all eQTLs
  - eqtl_max_coloc_llr_local # max log-likelihood ratio value for each (study, locus, gene) aggregating over all eQTLs
  - eqtl_max_coloc_llr_nbh # max log-likelihood ratio value for each (study, locus) aggregating over all eQTLs
  - pqtl_max_coloc_clpp_local # max clpp for each (study, locus, gene) aggregating over all pQTLs
  - pqtl_max_coloc_clpp_nbh # max clpp for each (study, locus) aggregating over all pQTLs
  - pqtl_max_coloc_llr_local # max log-likelihood ratio value for each (study, locus, gene) aggregating over all pQTLs
  - pqtl_max_coloc_llr_nbh # max log-likelihood ratio value for each (study, locus) aggregating over all pQTLs
  - sqtl_max_coloc_clpp_local # max clpp for each (study, locus, gene) aggregating over all sQTLs
  - sqtl_max_coloc_clpp_nbh # max clpp for each (study, locus) aggregating over all sQTLs
  - sqtl_max_coloc_llr_local # max log-likelihood ratio value for each (study, locus, gene) aggregating over all sQTLs
  - sqtl_max_coloc_llr_nbh # max log-likelihood ratio value for each (study, locus) aggregating over all sQTLs
gene_interactions_path: /Users/irenelopez/MEGAsync/EBI/repos/genetics_etl_python/mock_data/interaction
hyperparameters:
  max_depth: 5
