_target_: otg.v2g.V2GStep
defaults:
   - /etl: local
   - /dataset@variant_index: variant_index_from_file
   - /dataset@variant_annotation: variant_annotation_from_file
   - /dataset@gene_index: gene_index_from_file
#Defaults
liftover_max_length_difference: 100
approved_biotypes:
  - protein_coding
  - 3prime_overlapping_ncRNA
  - antisense
  - bidirectional_promoter_lncRNA
  - IG_C_gene
  - IG_D_gene
  - IG_J_gene
  - IG_V_gene
  - lincRNA
  - macro_lncRNA
  - non_coding
  - sense_intronic
  - sense_overlapping

#Hardcoded config
vep_consequences_path: /path/to/dataset/vep_consequences
# # Originally gs://genetics-portal-input/v2g_input/grch37_to_grch38.over.chain
# liftover_chain_file: ${etl.inputs}/v2g_input/grch37_to_grch38.over.chain
liftover_chain_file_path: /path/to/dataset/liftover_chain_file
# # An atlas of active enhancers across human cell types and tissues
# # Originally: gs://genetics-portal-input/v2g_input/andersson2014/enhancer_tss_associations.bed
anderson_path: /path/to/dataset/anderson
# # Lineage-Specific Genome Architecture Links Enhancers and Non-coding Disease Variants to Target Gene Promoters
# # Originally gs://genetics-portal-input/v2g_input/javierre_2016_preprocessed.parquet
javierre_path: /path/to/dataset/javierre
# # A compendium of promoter-centered long-range chromatin interactions in the human genome
# # Originally gs://genetics-portal-raw/pchic_jung2019/jung2019_pchic_tableS3.csv
jung_path: /path/to/dataset/jung
# # The accessible chromatin landscape of the human genome
# # Originally: gs://genetics-portal-input/v2g_input/thurman2012/genomewideCorrs_above0.7_promoterPlusMinus500kb_withGeneNames_32celltypeCategories.bed8.gz
thurnman_path: /path/to/dataset/thurnman

output_path: /path/to/dataset/v2g
