_target_: otg.method.locus_to_gene.LocusToGeneModel
run_mode: train

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

hyperparameters:
  max_depth: 5
  loss_function: logloss

inputs:
  _target_: otg.gold_standard.GoldStandard
  _partial_: true
  gold_standard_curation: gs://genetics_etl_python_playground/input/l2g/gold_standard/curation.json
  gene_interactions: gs://open-targets-pre-data-releases/23.02/output/etl/parquet/interactions
  study_locus: gs://genetics_etl_python_playground/input/l2g_input/mock_study_locus
feature_inputs:
  v2g: gs://genetics_etl_python_playground/input/l2g_input/mock_v2g
  colocalisation: gs://genetics_etl_python_playground/input/l2g_input/mock_colocalisation
  study_index: gs://genetics_etl_python_playground/input/l2g_input/mock_study_index
outputs:
  model: gs://genetics_etl_python_playground/output/XX.XX/l2g/model
  predictions: gs://genetics_etl_python_playground/output/l2g/predictions
