# Input/Output paths
version: XX.XX
inputs: gs://genetics_etl_python_playground/input
outputs: gs://genetics_etl_python_playground/output/python_etl/parquet/${datasets.version}

# Input datasets
chain_37_38: ${datasets.inputs}/v2g_input/grch37_to_grch38.over.chain
target_index: ${datasets.inputs}/v2g_input/targets_correct_tss
vep_consequences: gs://genetics-portal-data/lut/vep_consequences.tsv
anderson: gs://genetics-portal-input/v2g_input/andersson2014/enhancer_tss_associations.bed
javierre: gs://genetics-portal-input/v2g_input/javierre_2016_preprocessed.parquet
jung: gs://genetics-portal-raw/pchic_jung2019/jung2019_pchic_tableS3.csv
thurman: gs://genetics-portal-input/v2g_input/thurman2012/genomewideCorrs_above0.7_promoterPlusMinus500kb_withGeneNames_32celltypeCategories.bed8.gz
catalog_associations: ${datasets.inputs}/v2d/gwas_catalog_v1.0.2-associations_e110_r2023-09-11.tsv
catalog_studies: ${datasets.inputs}/v2d/gwas-catalog-v1.0.3-studies-r2023-09-11.tsv
catalog_ancestries: ${datasets.inputs}/v2d/gwas-catalog-v1.0.3-ancestries-r2023-09-11.tsv
catalog_sumstats_lut: ${datasets.inputs}/v2d/harmonised_list-r2023-09-11.txt
ukbiobank_manifest: gs://genetics-portal-input/ukb_phenotypes/neale2_saige_study_manifest.190430.tsv
l2g_gold_standard_curation: ${datasets.inputs}/l2g/gold_standard/curation.json
gene_interactions: ${datasets.inputs}/l2g/interaction # 23.09 data

# Output datasets
gene_index: ${datasets.outputs}/gene_index
variant_annotation: ${datasets.outputs}/variant_annotation
variant_index: ${datasets.outputs}/variant_index
study_locus: ${datasets.outputs}/study_locus
study_index: ${datasets.outputs}/study_index
summary_statistics: ${datasets.outputs}/summary_statistics
study_locus_overlap: ${datasets.outputs}/study_locus_overlap
colocalisation: ${datasets.outputs}/colocalisation
v2g: ${datasets.outputs}/v2g
ld_index: ${datasets.outputs}/ld_index
catalog_study_index: ${datasets.study_index}/catalog_curated
catalog_study_locus: ${datasets.credible_set}/catalog_curated
finngen_study_index: ${datasets.study_index}/finngen
finngen_summary_stats: ${datasets.summary_statistics}/finngen
from_sumstats_study_locus: ${datasets.study_locus}/from_sumstats
ukbiobank_study_index: ${datasets.study_index}/ukbiobank
l2g_model: ${datasets.outputs}/l2g_model
l2g_predictions: ${datasets.outputs}/l2g_predictions

# Constants
finngen_release_prefix: FINNGEN_R9
finngen_sumstat_url_prefix: gs://finngen-public-data-r9/summary_stats/finngen_R9_
finngen_sumstat_url_suffix: .gz
