
# Input/Output paths
version: XX.XX
inputs: gs://genetics_etl_python_playground/input
outputs: gs://genetics_etl_python_playground/output/python_etl/parquet/${datasets.version}

# Input datasets
gnomad_gnomes: gs://gcp-public-data--gnomad/release/3.1.2/ht/genomes/gnomad.genomes.v3.1.2.sites.ht
chain_hail_38_37: gs://hail-common/references/grch38_to_grch37.over.chain.gz
chain_hail_37_38: gs://hail-common/references/grch37_to_grch38.over.chain.gz
chain_37_38: ${datasets.inputs}/v2g_input/grch37_to_grch38.over.chain
target_index: ${datasets.inputs}/v2g_input/targets_correct_tss
vep_consequences: gs://genetics-portal-data/lut/vep_consequences.tsv
anderson: gs://genetics-portal-input/v2g_input/andersson2014/enhancer_tss_associations.bed
javierre: gs://genetics-portal-input/v2g_input/javierre_2016_preprocessed.parquet
jung: gs://genetics-portal-raw/pchic_jung2019/jung2019_pchic_tableS3.csv
thrunman: gs://genetics-portal-input/v2g_input/thurman2012/genomewideCorrs_above0.7_promoterPlusMinus500kb_withGeneNames_32celltypeCategories.bed8.gz
catalog_associations: ${datasets.inputs}/v2d/gwas_catalog_v1.0.2-associations_e107_r2022-11-29.tsv
catalog_studies: ${datasets.inputs}/v2d/gwas-catalog-v1.0.3-studies-r2022-11-29.tsv
catalog_ancestries: ${datasets.inputs}/v2d/gwas-catalog-v1.0.3-ancestries-r2022-11-29.tsv
catalog_sumstats_lut: ${datasets.inputs}/v2d/harmonised_list.txt
finngen_phenotype_table_url: https://r8.finngen.fi/api/phenos
# Templates
ld_index_raw_template: gs://gcp-public-data--gnomad/release/2.1.1/ld/gnomad.genomes.r2.1.1.{POP}.common.ld.variant_indices.ht
ld_matrix_template: gs://gcp-public-data--gnomad/release/2.1.1/ld/gnomad.genomes.r2.1.1.{POP}.common.adj.ld.bm

# Output datasets
gene_index: ${datasets.outputs}/gene_index/gene_index
variant_annotation: ${datasets.outputs}/variant_annotation
variant_index: ${datasets.outputs}/variant_index
study_locus: ${datasets.outputs}/study_locus
colocalisation: ${datasets.outputs}/colocalisation
v2g: ${datasets.outputs}/v2g
ld_index: ${datasets.outputs}/ld_index
catalog_study_index: ${datasets.outputs}/catalog_study_index
catalog_study_locus: ${datasets.outputs}/catalog_study_locus
finngen_study_index: ${datasets.outputs}/finngen_study_index
# Templates
ld_index_template: ${datasets.outputs}/gnomad_r2.1.1.{POP}.common.ld.variant_indices.parquet
finngen_release_prefix: FINNGEN_R8_
finngen_sumstat_url_prefix: https://storage.googleapis.com/finngen-public-data-r8/summary_stats/finngen_R8_
finngen_sumstat_url_suffix: .gz
