# Release specific configuration:
release_version: "24.01"
release_folder: gs://genetics_etl_python_playground/releases/${datasets.release_version}

inputs: gs://genetics_etl_python_playground/input
outputs: gs://genetics_etl_python_playground/output/python_etl/parquet/${datasets.version}

## Datasets:
gwas_catalog_dataset: gs://gwas_catalog_data
catalog_associations: ${datasets.gwas_catalog_dataset}/curated_inputs/gwas-catalog-associations_ontology-annotated.tsv
catalog_studies:
  - ${datasets.gwas_catalog_dataset}/curated_inputs/gwas-catalog-download-studies.tsv
  - ${datasets.gwas_catalog_dataset}/curated_inputs/gwas-catalog-unpublished-studies.tsv
catalog_ancestries:
  - ${datasets.gwas_catalog_dataset}/curated_inputs/gwas-catalog-download-ancestries.tsv
  - ${datasets.gwas_catalog_dataset}/curated_inputs/gwas-catalog-unpublished-ancestries.tsv
catalog_sumstats_lut: ${datasets.gwas_catalog_dataset}/curated_inputs/harmonised_list.txt
gwas_catalog_study_curation: ${datasets.gwas_catalog_dataset}/manifest/GWAS_Catalog_study_curation.tsv

# Input datasets
chain_37_38: ${datasets.inputs}/v2g_input/grch37_to_grch38.over.chain
target_index: ${datasets.inputs}/v2g_input/targets_correct_tss
vep_consequences: gs://genetics-portal-data/lut/vep_consequences.tsv
anderson: gs://genetics-portal-input/v2g_input/andersson2014/enhancer_tss_associations.bed
javierre: gs://genetics-portal-input/v2g_input/javierre_2016_preprocessed.parquet
jung: gs://genetics-portal-raw/pchic_jung2019/jung2019_pchic_tableS3.csv
thurman: gs://genetics-portal-input/v2g_input/thurman2012/genomewideCorrs_above0.7_promoterPlusMinus500kb_withGeneNames_32celltypeCategories.bed8.gz

gene_interactions: ${datasets.inputs}/l2g/interaction # 23.09 data
eqtl_catalogue_paths_imported: ${datasets.inputs}/preprocess/eqtl_catalogue/tabix_ftp_paths_imported.tsv

# Output datasets
gene_index: ${datasets.outputs}/gene_index
variant_annotation: ${datasets.outputs}/variant_annotation
study_locus: ${datasets.outputs}/study_locus
summary_statistics: ${datasets.outputs}/summary_statistics
study_locus_overlap: ${datasets.outputs}/study_locus_overlap

ld_index: ${datasets.outputs}/ld_index
catalog_study_index: ${datasets.study_index}/catalog
catalog_study_locus: ${datasets.study_locus}/catalog_study_locus

finngen_study_index: ${datasets.study_index}/finngen
finngen_summary_stats: ${datasets.summary_statistics}/finngen
from_sumstats_study_locus: ${datasets.study_locus}/from_sumstats
from_sumstats_pics: ${datasets.credible_set}/from_sumstats

# ETL output datasets:
l2g_gold_standard_curation: ${datasets.release_folder}/locus_to_gene_gold_standard.json
l2g_model: ${datasets.release_folder}/locus_to_gene_model
l2g_predictions: ${datasets.release_folder}/locus_to_gene_predictions
colocalisation: ${datasets.release_folder}/colocalisation
study_index: ${datasets.release_folder}/study_index
variant_index: ${datasets.release_folder}/variant_index
credible_set: ${datasets.release_folder}/credible_set
v2g: ${datasets.release_folder}/variant_to_gene
