coloc:
  # Credible sets (Coloc input)
  credible_set: gs://ot-team/dochoa/220224_merged_credset/

  # coloc parameters:
  # priorc1 Prior on variant being causal for trait 1
  priorc1: 1e-4
  # priorc2 Prior on variant being causal for trait 2
  priorc2: 1e-4
  # priorc12 Prior on variant being causal for traits 1 and 2
  priorc12: 1e-5

  # For annotation of the outputs
  phenotype_id_gene: gs://ot-team/dochoa/phenotype_id_gene_luts/
  sumstats_filtered: gs://genetics-portal-dev-sumstats/filtered/significant_window_2mb_union

  # Outputs
  output: gs://ot-team/dochoa/coloc

intervals:
  liftover_chain_file: gs://genetics-portal-input/v2g_input/grch37_to_grch38.over.chain
  gene_index: gs://genetics-portal-input/v2g_input/geneset.protein_coding.parquet
  max_length_difference: 100
  output: gs://genetics-portal-dev-data/dev_intervals

  # An atlas of active enhancers across human cell types and tissues
  anderson_file: gs://genetics-portal-input/v2g_input/andersson2014/enhancer_tss_associations.bed

  # Lineage-Specific Genome Architecture Links Enhancers and Non-coding Disease Variants to Target Gene Promoters
  javierre_dataset: gs://genetics-portal-input/v2g_input/javierre_2016_preprocessed.parquet

  # A compendium of promoter-centered long-range chromatin interactions in the human genome
  jung_file: gs://genetics-portal-raw/pchic_jung2019/jung2019_pchic_tableS3.csv

  # The accessible chromatin landscape of the human genome
  thurman_file: gs://genetics-portal-input/v2g_input/thurman2012/genomewideCorrs_above0.7_promoterPlusMinus500kb_withGeneNames_32celltypeCategories.bed8.gz
