- id: "ot_colocalisation_ecaviar"
- id: "ot_colocalisation_coloc"
- id: "ot_locus_to_gene_train"
  prerequisites:
    - "ot_colocalisation_ecaviar"
    - "ot_colocalisation_coloc"
- id: "ot_locus_to_gene_predict"
  prerequisites:
    - "ot_locus_to_gene_train"
    - "ot_colocalisation_ecaviar"
    - "ot_colocalisation_coloc"
