- id: "ot_gene_index"
- id: "ot_variant_index"
- id: "ot_variant_to_gene"
  prerequisites:
    - "ot_variant_index"
    - "ot_gene_index"
- id: "ot_locus_to_gene_train"
  prerequisites:
    - "ot_variant_index"
    - "ot_variant_to_gene"
- id: "ot_locus_to_gene_predict"
  prerequisites:
    - "ot_variant_index"
    - "ot_variant_to_gene"
