- id: "ot_gene_index"
- id: "ot_gwas_catalog"
- id: "ot_variant_index"
  prerequisites:
    - "ot_gwas_catalog"
- id: "ot_variant_to_gene"
  prerequisites:
    - "ot_variant_index"
    - "ot_gene_index"
- id: "ot_study_locus_overlap"
  prerequisites:
    - "ot_gwas_catalog"
- id: "ot_locus_to_gene"
  prerequisites:
    - "ot_gwas_catalog"
    - "ot_variant_index"
    - "ot_variant_to_gene"
    - "ot_overlaps"
