- id: "gene_index"
- id: "gwas_catalog"
- id: "variant_index"
  prerequisites:
    - "gwas_catalog"
- id: "v2g"
  prerequisites:
    - "variant_index"
    - "gene_index"
- id: "study_locus_overlap"
  prerequisites:
    - "gwas_catalog"
- id: "locus_to_gene"
  prerequisites:
    - "gwas_catalog"
    - "variant_index"
    - "v2g"
    - "study_locus_overlap"
