- id: "gene_index"
- id: "variant_annotation"
- id: "ld_index"
- id: "gwas_catalog"
  prerequisites:
    - "variant_annotation"
    - "ld_index"
- id: "variant_index"
  prerequisites:
    - "variant_annotation"
    - "gwas_catalog"
- id: "v2g"
  prerequisites:
    - "variant_index"
    - "variant_annotation"
    - "gene_index"
- id: "finngen"
- id: "ukbiobank"
