- id: "gene_index"
- id: "gwas_catalog"
  tasks:
    - id: "gwas_catalog_ingestion"
    - id: "clump"
      args:
        input_path: study_locus/catalog_study_locus
        study_index_path: catalog_study_index
        clumped_study_locus_path: study_locus/catalog_study_locus
    - id: "pics"
      args:
        study_locus_ld_annotated_in: study_locus/catalog_study_locus
        picsed_study_locus_out: credible_set/catalog_curated
- id: "variant_index"
  prerequisites:
    - "gwas_catalog"
- id: "v2g"
  prerequisites:
    - "variant_index"
    - "gene_index"
- id: "ukbiobank"
- id: "study_locus_overlap"
  prerequisites:
    - "gwas_catalog"
    - "ukbiobank"
- id: "locus_to_gene"
  prerequisites:
    - "gwas_catalog"
    - "ukbiobank"
    - "variant_index"
    - "v2g"
    - "study_locus_overlap"
