coloc:
  # Credible sets (Coloc input)
  credible_set: gs://genetics-portal-dev-analysis/dsuveges/test_credible_set_chr22.parquet # chr22 parquet

  # TODO: once the full credible set is in parquet. Add 2 hydra configs one for chr22 and one for all
  # https://hydra.cc/docs/tutorials/basic/your_first_app/config_groups/
  # credible_set: gs://genetics-portal-dev-staging/finemapping/220224_merged/credset/ # all in JSON

  # coloc parameters:
  # priorc1 Prior on variant being causal for trait 1
  priorc1: 1e-4
  # priorc2 Prior on variant being causal for trait 2
  priorc2: 1e-4
  # priorc12 Prior on variant being causal for traits 1 and 2
  priorc12: 1e-5

  # For annotation of the outputs
  phenotype_id_gene: gs://ot-team/dochoa/phenotype_id_gene_luts/
  sumstats_filtered: gs://genetics-portal-dev-sumstats/filtered/significant_window_2mb_union

  # Outputs
  output: gs://ot-team/dochoa/coloc