coloc:
  # Credible sets (Coloc input)
  credible_set: gs://ot-team/dochoa/220224_merged_credset/chrom=22/

  # coloc parameters:
  # priorc1 Prior on variant being causal for trait 1
  priorc1: 1e-4
  # priorc2 Prior on variant being causal for trait 2
  priorc2: 1e-4
  # priorc12 Prior on variant being causal for traits 1 and 2
  priorc12: 1e-5

  # For annotation of the outputs
  phenotype_id_gene: gs://ot-team/dochoa/phenotype_id_gene_luts/
  sumstats_filtered: gs://genetics-portal-dev-sumstats/filtered/significant_window_2mb_union

  # Outputs
  output: gs://ot-team/dochoa/coloc