defaults:
  - base_variant_annotation_gnomad
gnomad_file: gs://gcp-public-data--gnomad/release/3.1.2/ht/genomes/gnomad.genomes.v3.1.2.sites.ht
chain_file: gs://hail-common/references/grch38_to_grch37.over.chain.gz
populations:
  - afr  # African-American
  - amr  # American Admixed/Latino
  - ami  # Amish ancestry
  - asj  # Ashkenazi Jewish
  - eas  # East Asian
  - fin  # Finnish
  - nfe  # Non-Finnish European
  - mid  # Middle Eastern
  - sas  # South Asian
  - oth  # Other
path: "path/to/dataset/variant_annotation"
