

default:
  master_machine_type: "n1-highmem-32"
  single_node: true
  max_idle: 10m

coloc:
  master_machine_type: "n1-highmem-64"
  single_node: true
  max_idle: 10m

variant_annotation:
  master_machine_type: 'n1-highmem-96'
  single_node: true
  max_idle: 10m

v2g:
  master_machine_type: 'n1-highmem-64'
  single_node: true
  max_idle: 10m
