# This workflow will run lint
name: All lints
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: src/
        use-pylint: true
        use-pycodestyle: true
        use-flake8: false
        use-black: true
        use-mypy: false
        use-isort: true