name: Update Python Poetry packages

on:
  # Allow manual triggers.
  workflow_dispatch:

  # Automatically run once a week.
  schedule:
    - cron: "0 7 * * MON"

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Update Python Poetry package
        uses: dishapatel010/action-poetry-package-update@V2.0.1
        with:
          python-version: 3.10.8
          base-branch: main
